const { ROLES } = require("../constant/constant")
const auth = require("../middleware/auth.middleware")
const permissionCheck = require("../middleware/rbac.middleware")
const {uploader,uploaderPath} = require("../middleware/uploader.middleware")
const bodyValidator = require("../middleware/validator.middleware")
const authCtrl = require("./auth.controller")
const { registerSchema, verifyOtpSchema, passwordSchema, resendOtpSchema, loginUserSchema, updateuserSchema } = require("./auth.request")
const authRouter = require("express").Router()
authRouter.post("/register",uploaderPath("users"),uploader.single("profile"),bodyValidator(registerSchema,"profile"),authCtrl.register)
authRouter.post("/verify-otp",bodyValidator(verifyOtpSchema),authCtrl.verifyOTP)
authRouter.post("/resend-otp",bodyValidator(resendOtpSchema),authCtrl.resendOTP)
authRouter.post("/activate/:token",bodyValidator(passwordSchema),authCtrl.activatePassword)
authRouter.post("/login",bodyValidator(loginUserSchema),authCtrl.loginUser)
authRouter.get("/me",auth,permissionCheck(ROLES.CUSTOMER),authCtrl.profile)
authRouter.put("/user/:id",auth,permissionCheck(ROLES.CUSTOMER),uploader.single("profile"),bodyValidator(updateuserSchema),authCtrl.updateuser)
module.exports= authRouter